### ISSUE TITLE
gulp preview depends on meteor-build/ directory

### ISSUE THREAD

**Issue by felipebueno** [YuHuaiChen/meteor-electron-client#2]
Hi, @YuHuaiChen 

First of all, thanks for this great project. It's very useful :)

Now to the issue. Running `gulp preview` after cloning the repository doesn't work. I had to create the directory meteor-build/ and then it works fine :)

So, maybe you could update your `.gitignore` to ignore `meteor-build/*` instead of `meteor-build/`. Does this make sense or am I missing something?

Thanks again,

Felipe

**Comment by DaxChen** [comment]
Oh, sorry if the doc isn't clear...

`gulp preview` is just a electron box pointing to `localhost:3000`, so you have to manually run `meteor` in the `meteor/` directory and run `gulp preview` in another terminal. This is just for development purpose if you want to see what your app looks like, but don't want to wait for the build step every time you make some changes.

If you want to see your app being built, you should run `gulp` instead (the or gulp default)!

**Comment by DaxChen** [comment]
updated .gitignore by the way : )
